import { env } from "../../config/env.js";
import { EventCandidate, SourceSnippet } from "../../types/event.js";

const ATTENDEE_ESTIMATE_BY_CATEGORY: Record<string, number> = {
  AI: 300,
  CLOUD: 250,
  SECURITY: 200,
  FRONTEND: 200,
  MOBILE: 150,
  DATA: 250,
  DEVOPS: 200,
  COMMUNITY: 100,
};

const estimateAttendees = (category: string): number => {
  return ATTENDEE_ESTIMATE_BY_CATEGORY[category.toUpperCase()] ?? 150;
};

const inferCategory = (rawText: string): EventCandidate["category"] => {
  const text = rawText.toLowerCase();
  if (text.includes("kubernetes") || text.includes("cloud")) return "CLOUD";
  if (text.includes("security")) return "SECURITY";
  if (text.includes("frontend") || text.includes("react")) return "FRONTEND";
  if (text.includes("mobile") || text.includes("react native")) return "MOBILE";
  if (text.includes("data")) return "DATA";
  if (text.includes("devops")) return "DEVOPS";
  if (text.includes("ai")) return "AI";
  return "COMMUNITY";
};

const slugify = (value: string): string => {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
};

const SNIPPET_FIELD_KEYS = [
  "Event",
  "Summary",
  "Date",
  "End",
  "City",
  "Country",
  "Venue",
  "Price",
  "Page URL",
  "Page Text",
];

const escapeRegExp = (value: string): string => {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
};

const extractLineValue = (rawText: string, key: string): string | null => {
  const otherKeysPattern = SNIPPET_FIELD_KEYS
    .filter((field) => field.toLowerCase() !== key.toLowerCase())
    .map((field) => escapeRegExp(field))
    .join("|");

  const escapedKey = escapeRegExp(key);
  const regex = new RegExp(
    `${escapedKey}:\\s*([\\s\\S]*?)(?=\\r?\\n|\\s+(?:${otherKeysPattern}):|$)`,
    "i",
  );
  const match = rawText.match(regex);
  return match?.[1]?.trim() ?? null;
};

const toSafeIsoDate = (value: string | null, fallback: Date): string => {
  if (!value) {
    return fallback.toISOString();
  }

  const candidate = new Date(value.trim());
  if (Number.isNaN(candidate.getTime())) {
    return fallback.toISOString();
  }

  return candidate.toISOString();
};

const fallbackExtract = (snippets: SourceSnippet[]): EventCandidate[] => {
  return snippets.map((snippet, index) => {
    const title = extractLineValue(snippet.rawText, "Event") ?? `Tech Event ${index + 1}`;
    const summary =
      extractLineValue(snippet.rawText, "Summary") ??
      "AI discovered this event from external sources.";
    const startDate = toSafeIsoDate(
      extractLineValue(snippet.rawText, "Date"),
      new Date(),
    );
    const endDate = toSafeIsoDate(
      extractLineValue(snippet.rawText, "End"),
      new Date(startDate),
    );
    const city = extractLineValue(snippet.rawText, "City") ?? "Remote";
    const country = extractLineValue(snippet.rawText, "Country") ?? "Global";
    const venue = extractLineValue(snippet.rawText, "Venue") ?? "TBA";
    const priceLabel = extractLineValue(snippet.rawText, "Price") ?? "Free";
    const category = inferCategory(snippet.rawText);
    const id = `${slugify(title)}-${startDate.slice(0, 10)}`;

    return {
      id,
      title,
      summary,
      description: summary,
      category,
      sourceType: snippet.sourceType,
      sourceName: snippet.sourceName,
      sourceUrl: snippet.sourceUrl,
      registrationUrl: snippet.registrationUrl,
      location: `${city}, ${country}`,
      venue,
      city,
      country,
      startDate,
      endDate,
      imageUrl: snippet.imageUrl,
      tags: [category.toLowerCase(), "tech", "community"],
      priceLabel,
      attendeeEstimate: estimateAttendees(category),
      aiConfidence: 0.6,
      aiSummary:
        "Generated by fallback extraction. Configure OpenAI or Gemini for richer parsing.",
    };
  });
};

const parseJsonArrayFromText = (input: string): unknown[] | null => {
  const start = input.indexOf("[");
  const end = input.lastIndexOf("]");
  if (start === -1 || end === -1 || end <= start) {
    return null;
  }

  const maybeJson = input.slice(start, end + 1);
  try {
    const parsed = JSON.parse(maybeJson);
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
};

const normalizeCandidate = (
  raw: Record<string, unknown>,
  fallback: EventCandidate,
): EventCandidate => {
  const safeString = (value: unknown, fallbackValue: string): string => {
    return typeof value === "string" && value.trim().length > 0
      ? value.trim()
      : fallbackValue;
  };

  const safeNumber = (value: unknown, fallbackValue: number): number => {
    return typeof value === "number" && Number.isFinite(value)
      ? value
      : fallbackValue;
  };

  const category = safeString(raw.category, fallback.category).toUpperCase();
  const sourceType = safeString(raw.sourceType, fallback.sourceType).toUpperCase();
  const tags =
    Array.isArray(raw.tags) && raw.tags.every((tag) => typeof tag === "string")
      ? raw.tags
      : fallback.tags;

  return {
    ...fallback,
    title: safeString(raw.title, fallback.title),
    summary: safeString(raw.summary, fallback.summary),
    description: safeString(raw.description, fallback.description),
    category:
      category === "AI" ||
      category === "CLOUD" ||
      category === "SECURITY" ||
      category === "FRONTEND" ||
      category === "MOBILE" ||
      category === "DATA" ||
      category === "DEVOPS" ||
      category === "COMMUNITY"
        ? category
        : fallback.category,
    sourceType:
      sourceType === "SOCIAL_MEDIA" ||
      sourceType === "WEBSITE" ||
      sourceType === "NEWSLETTER" ||
      sourceType === "COMMUNITY"
        ? sourceType
        : fallback.sourceType,
    sourceUrl: safeString(raw.sourceUrl, fallback.sourceUrl),
    registrationUrl: safeString(raw.registrationUrl, fallback.registrationUrl),
    location: safeString(raw.location, fallback.location),
    venue: safeString(raw.venue, fallback.venue),
    city: safeString(raw.city, fallback.city),
    country: safeString(raw.country, fallback.country),
    startDate: safeString(raw.startDate, fallback.startDate),
    endDate: safeString(raw.endDate, fallback.endDate),
    imageUrl: safeString(raw.imageUrl, fallback.imageUrl),
    tags,
    priceLabel: safeString(raw.priceLabel, fallback.priceLabel),
    attendeeEstimate: safeNumber(raw.attendeeEstimate, fallback.attendeeEstimate),
    aiConfidence: Math.min(Math.max(safeNumber(raw.aiConfidence, 0.87), 0.5), 1),
    aiSummary: safeString(
      raw.aiSummary,
      "Generated by AI extraction from configured source snippets.",
    ),
  };
};

const buildPrompt = (snippets: SourceSnippet[]): string => {
  return `You are extracting structured tech event data from snippets for an Africa-focused events platform.
Return ONLY JSON array and no prose.
Each item must include:
id,title,summary,description,category,sourceType,sourceName,sourceUrl,registrationUrl,location,venue,city,country,startDate,endDate,imageUrl,tags,priceLabel,attendeeEstimate,aiConfidence,aiSummary
Allowed category values: AI,CLOUD,SECURITY,FRONTEND,MOBILE,DATA,DEVOPS,COMMUNITY
Allowed sourceType values: SOCIAL_MEDIA,WEBSITE,NEWSLETTER,COMMUNITY
IMPORTANT: Only extract events that are physically taking place in an African country, OR online/virtual events run by an Africa-based organisation with a primary African audience. Set city and country to the African location. If the event is online, set country to the organising body's country if African, otherwise skip it.
Target opportunities to extract: tech events, meetups, workshops, mentorship sessions, hackathons, bootcamps, community opportunities.
Snippets:
${JSON.stringify(snippets)}`;
};

const extractWithOpenAi = async (
  snippets: SourceSnippet[],
): Promise<EventCandidate[] | null> => {
  if (!env.OPENAI_API_KEY) {
    return null;
  }

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-4.1-mini",
      input: buildPrompt(snippets),
    }),
  });

  if (!response.ok) {
    return null;
  }

  const data = (await response.json()) as {
    output_text?: string;
  };
  if (!data.output_text) {
    return null;
  }

  const parsed = parseJsonArrayFromText(data.output_text);
  if (!parsed) {
    return null;
  }

  const fallback = fallbackExtract(snippets);
  return fallback.map((item, index) => {
    const source = parsed[index];
    if (!source || typeof source !== "object") {
      return item;
    }
    return normalizeCandidate(source as Record<string, unknown>, item);
  });
};

const extractWithGemini = async (
  snippets: SourceSnippet[],
): Promise<EventCandidate[] | null> => {
  if (!env.GEMINI_API_KEY) {
    return null;
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${env.GEMINI_API_KEY}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: buildPrompt(snippets),
              },
            ],
          },
        ],
      }),
    },
  );

  if (!response.ok) {
    return null;
  }

  const data = (await response.json()) as {
    candidates?: Array<{
      content?: {
        parts?: Array<{ text?: string }>;
      };
    }>;
  };

  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    return null;
  }

  const parsed = parseJsonArrayFromText(text);
  if (!parsed) {
    return null;
  }

  const fallback = fallbackExtract(snippets);
  return fallback.map((item, index) => {
    const source = parsed[index];
    if (!source || typeof source !== "object") {
      return item;
    }
    return normalizeCandidate(source as Record<string, unknown>, item);
  });
};

export const extractEventsFromSnippets = async (
  snippets: SourceSnippet[],
): Promise<EventCandidate[]> => {
  try {
    if (env.AI_PROVIDER === "openai") {
      const openAiResult = await extractWithOpenAi(snippets);
      if (openAiResult) {
        return openAiResult;
      }
    }

    if (env.AI_PROVIDER === "gemini") {
      const geminiResult = await extractWithGemini(snippets);
      if (geminiResult) {
        return geminiResult;
      }
    }
  } catch {
    // fall back when upstream provider fails
  }

  return fallbackExtract(snippets);
};
